---
title: " Repository Dashboard"
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include = FALSE}
library(flexdashboard)
library(gh)
library(jsonlite)
library(lubridate)
library(dplyr)
library(purrr)
library(tibble)
library(codetools) # there was a weird error on connect that needed this
library(DT)
library(tidyversedashboard)
library(tidyr)
library(sparkline)
```

```{r pr_stats, include=FALSE, cache = TRUE}
pr_data <- bind_rows(
  org_pr("r-lib"),
  org_pr("tidyverse"),
  org_pr("r-dbi"))

prs <- pr_data %>%
  filter(created > today() - ddays(30)) %>%
  select(repo, number, author, reviewer) %>%
  filter(is.na(reviewer) | author != reviewer) %>%
  unique()

pr_authors <- prs %>% select(-reviewer) %>% unique() %>% group_by(author)
pr_reviewers <- prs %>% select(-author) %>% unique() %>% group_by(reviewer)
pr_pairs <- prs %>% na.omit() %>% group_by(author, reviewer) %>% tally(sort = TRUE)
```

```{r repo_stats, include = FALSE, cache = TRUE}
data <- list(
  org_data("tidyverse"),
  org_data("r-lib"),
  org_data("r-dbi"))
repo_summary <- bind_rows(map(data, "summary"))
issues <- bind_rows(map(data, "issues"))
```

Repository statistics
=====================================
```{r}

aliases <- c("Jim Hester <james.f.hester@gmail.com>" = "Jim Hester <jim.hester@rstudio.com>", "Jim Hester <james.hester@rstudio.com>", "Gabor Csardi <csardi.gabor@gmail.com>" = "Gábor Csárdi <csardi.gabor@gmail.com>")

remove_aliases <- function(x, y) {
  m <- x %in% names(y)
  x[m] <- y[x[m]]
  x
}

num_hard_dependencies <- function(x) {
  sum(x$get_deps()$type %in% c("Depends", "Imports", "LinkingTo"))
}

num_soft_dependencies <- function(x) {
  sum(x$get_deps()$type %in% c("Suggests", "Enhances"))
}

num_downloads <- function(x, when = "last-week") {
  # only lookup packages that are valid package names
  valid_pkgs <- grepl(paste0("^", .standard_regexps()$valid_package_name, "$"), x)
  res <- cranlogs::cran_downloads(x[valid_pkgs], "last-week")
  count_per_package <- res %>% group_by(package) %>% tally(wt = count)
  out <- numeric(length(x))
  out[valid_pkgs] <- left_join(tibble(package = x[valid_pkgs]), count_per_package)$n
  out
}

# This could be slow for many many repos, but for the ~100 or so we have now it
# is not so bad.
weekly_commits <- possibly(otherwise = NA_integer_, function(org, package) {
  map_int(gh::gh("/repos/:org/:package/stats/commit_activity", org = org, package = package), "total")
})

summary_table <- repo_summary %>%
  rename("\U1F44D" = p1, "package" = "repo") %>%
  mutate(
    weekly_downloads = num_downloads(.$package, "last-week"),
    maintainer = remove_aliases(map_chr(description, ~ if (length(.x)) .x$get_maintainer()), aliases),
    hard_deps = map_dbl(description, num_hard_dependencies),
    soft_deps = map_dbl(description, num_soft_dependencies),
    activity = map2(owner, package, weekly_commits)) %>%
  select(owner, package, maintainer, watchers, weekly_downloads, hard_deps, soft_deps, open_issues, prs, "\U1F44D", everything(), -description)

# A custom datatable with a sparkline column
dt <- datatable(summary_table, filter = "top", rownames = FALSE, escape = FALSE,
  options = list(
    columnDefs = list(list(
        targets = 13,
        render = JS("
          function(data, type, row, meta) {
            return '<span class=spark>' + data + '</span>'
          }"))),
    fnDrawCallback = JS("
      function (oSettings, json) { $('.spark:not(:has(canvas))').sparkline('html', {width: '100px', lineColor: '#DCAB49', fillColor: '#DBDED3', spotColor: '', minSpotColor: '', maxSpotColor: ''}) }")))
dt$dependencies <- append(dt$dependencies, htmlwidgets::getDependency("sparkline"))
dt
```

Issues
=====================================
```{r}
substitute_emoji <- function(x) {
  m <- gregexpr(":[^[:space:]]+:", x)

  regmatches(x, m) <- lapply(regmatches(x, m), function(xx) map_chr(gsub(":", "", xx), emo::ji))
  x
}

# linkify the titles, and replace emoji
issue_table <- mutate(issues,
  title = glue::glue('<a href="https://github.com/{owner}/{repo}/issues/{issue}">{title}</a>'),
  labels = substitute_emoji(map_chr(labels, paste, collapse = ", "))) %>%
  rename("\U1F44D" = p1)

datatable(issue_table,
  filter = "top",
  escape = c(-4),
  rownames = FALSE)
```

Pull request review counts
=====================================

Column
-------------------------------------
### PR authors
```{r}
datatable(tally(pr_authors, sort = TRUE))
```

Column
-------------------------------------
### PR reviewers
```{r}
datatable(tally(pr_reviewers, sort = TRUE))
```

Column
-------------------------------------
### PR pairs
```{r}
datatable(pr_pairs)
```
